# .air.toml
root = "."
tmp_dir = "tmp"
build_cmd = "go build"
binary = "./{{.AppName}}"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "node_modules", "public"]
include_ext = [".go", ".tpl", ".tmpl", ".html"]
